### ISSUE TITLE
About Test Set

### ISSUE THREAD

**Issue by kbtwo** [grimmlab/ProLaTherm#1]
May I ask if Test set 1 and Test set 2 in the paper can be found on this website? I have been searching for them for a long time but have not found them.

**Comment by kbtwo** [comment]
>May I ask if Test set 2 in the paper can be found on this website? I have been searching for it for a long time but have not found it. I only found Test set 1.

**Comment by fhaselbeck** [comment]
Dear kbtwo,

you are right, so far test set 1 and test set 2 were only available in combination of the full dataset with the index files.

We just uploaded two .csv files containing test set 1 and test set 2, respectively. You can find them here: https://github.com/grimmlab/ProLaTherm/tree/main/data/datasets_w_datasplits

Thanks!
